package spinnaker

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// resetGateURLCache evita que testes interfiram entre si (gateURLCache é estado de pacote
// compartilhado) — mesmo padrão de resetEKSTokenCache em internal/config/eks_token_test.go.
func resetGateURLCache(t *testing.T) {
	t.Helper()
	gateURLCacheMu.Lock()
	gateURLCache = make(map[string]gateURLCacheEntry)
	gateURLCacheMu.Unlock()
	t.Cleanup(func() {
		gateURLCacheMu.Lock()
		gateURLCache = make(map[string]gateURLCacheEntry)
		gateURLCacheMu.Unlock()
	})
}

// TestResolveGateURL_FormatoReal usa o mesmo formato de settings.js confirmado ao vivo contra
// spinnaker-hlg.viavarejo.com.br (ver seção 1 do plano).
func TestResolveGateURL_FormatoReal(t *testing.T) {
	resetGateURLCache(t)

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/settings.js" {
			http.NotFound(w, r)
			return
		}
		w.Header().Set("Content-Type", "application/javascript")
		w.Write([]byte(`
// WARNING
// This file was autogenerated, and _will_ be overwritten by Halyard.
'use strict';

var gateHost = 'https://spinnaker-hlg-api.viavarejo.com.br';
var authEnabled = 'true' === 'true';
`))
	}))
	defer srv.Close()

	got, err := ResolveGateURL(context.Background(), srv.Client(), srv.URL)
	if err != nil {
		t.Fatalf("erro inesperado: %v", err)
	}
	want := "https://spinnaker-hlg-api.viavarejo.com.br"
	if got != want {
		t.Errorf("ResolveGateURL() = %q, esperava %q", got, want)
	}
}

// TestResolveGateURL_Cache confirma que uma 2ª chamada não bate no servidor de novo.
func TestResolveGateURL_Cache(t *testing.T) {
	resetGateURLCache(t)

	calls := 0
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		calls++
		w.Write([]byte(`var gateHost = 'https://gate.example.com';`))
	}))
	defer srv.Close()

	for i := 0; i < 3; i++ {
		if _, err := ResolveGateURL(context.Background(), srv.Client(), srv.URL); err != nil {
			t.Fatalf("chamada %d: erro inesperado: %v", i, err)
		}
	}
	if calls != 1 {
		t.Errorf("esperava 1 chamada real ao settings.js (resto vindo do cache), teve %d", calls)
	}
}

// TestResolveGateURL_FormatoInesperado garante um erro claro (não um pânico nem um resultado
// vazio silencioso) quando o settings.js não tem o formato esperado.
func TestResolveGateURL_FormatoInesperado(t *testing.T) {
	resetGateURLCache(t)

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(`<html>não é um settings.js válido</html>`))
	}))
	defer srv.Close()

	_, err := ResolveGateURL(context.Background(), srv.Client(), srv.URL)
	if err == nil {
		t.Fatal("esperava erro pra settings.js sem 'var gateHost'")
	}
	if !strings.Contains(err.Error(), "gateHost") {
		t.Errorf("mensagem de erro pouco clara: %v", err)
	}
}

// TestResolveGateURL_TrimBarraFinal garante que a URL do Deck funciona com ou sem "/" final —
// exatamente como o usuário colou (com "/") na especificação do perfil (seção 10.1 do plano).
func TestResolveGateURL_TrimBarraFinal(t *testing.T) {
	resetGateURLCache(t)

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(`var gateHost = 'https://gate.example.com';`))
	}))
	defer srv.Close()

	got, err := ResolveGateURL(context.Background(), srv.Client(), srv.URL+"/")
	if err != nil {
		t.Fatalf("erro inesperado: %v", err)
	}
	if got != "https://gate.example.com" {
		t.Errorf("ResolveGateURL() = %q", got)
	}
}
